{
    'name': 'Custom Cash Incentive',
    'version': '1.0.0',
    'category': 'Sales',
    'sequence': 1,
    'summary': 'Custom Cash Incentive for Odoo v17',
    'description': """Custom Cash Incentive for Odoo v17""",
    'author': 'Ogroni Informatix Limited',
    'company': 'Ogroni Informatix Limited',
    'maintainer': 'Ogroni Informatix Limited',
    'website': 'https://ogroni.com/',
    'license': 'LGPL-3',
    'depends': ['web', 'base', 'account', 'sale_stock', 'hr'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'views/menu_views.xml',
        'views/cash_incentive.xml',
        'views/division_views.xml',
        'views/postcode_views.xml',
        'views/district_views.xml',
        'views/thana_views.xml',
        'wizards/report_cash_incentive.xml',
        'views/code_sequence_views.xml',
        'views/cash_incentive.xml',
        'views/incentive_bank.xml',
        'views/client_contract_views.xml',
        'views/account_journal_inherit_cash_incentive.xml',
        'views/inherited_account_move_inherit_cash_incentive_views.xml',
        'views/swift_message_views.xml',
        'views/invoice_terms_conditions_views.xml',
        'views/cash_incentive_invoice_details.xml',
        'views/inherited_product_tem_inherit_cash_incentive_views.xml',
        'views/currency_conversion_rate_views.xml',
        'views/inherited_currency_conversion_inherit_cash_incentive_views.xml',
        'views/erq_limit_views.xml',
        'views/inherited_res_partner_inherit_cash_incentive.xml',
        'views/basis_fee_configuration.xml',
        'wizards/swift_invoice_wizard_views.xml',
        'wizards/merge_invoice_wizard_views.xml',
        'wizards/en_rate_wizard_views.xml',
        'wizards/upload_invoice_wizard_views.xml',
        'wizards/cash_incentive_print_tree_views.xml',
        'reports/incentive_letter.xml',
        'reports/report_invoice.xml',
        'reports/voucher_report.xml',
        'reports/report_journal_entries_view.xml',
        'reports/incentive_pdf_report.xml',
        'reports/incentive_action_reports_tree.xml',
        'wizards/encashment_report_wizard_wizard_views.xml',
        'wizards/cash_incentive_summary_report_views.xml',
        'wizards/support_tools_incentive_wizard_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'cash_incentive/static/src/js/*',
            'cash_incentive/static/src/xml/*',
        ]
    },
    'installable': True,
    'application': True,
    'auto_install': False,
}
